apiVersion: v1
kind: Service
metadata:
  name: backend-service-2022bcd0053
spec:
  selector:
    app: expense-backend
  ports:
    - protocol: TCP
      port: 5000           # Port exposed inside the cluster
      targetPort: 5000     # Port your Node.js server listens on
      nodePort: 30007      # Optional - for external access in Minikube
  type: NodePort      # NodePort for accessing from host (curl, browser)
