apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy-2022bcd0053
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-backend
  template:
    metadata:
      labels:
        app: expense-backend
    spec:
      containers:
      - name: expense-backend
        image: 2022bcd0053-harshada
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config-2022bcd0053
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret-2022bcd0053
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret-2022bcd0053
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config-2022bcd0053
              key: name
