apiVersion: v1
kind: Secret
metadata:
  name: db-secret-2022bcd0053
type: Opaque
data:
  username: cm9vdA==            # base64 for "root"
  password: SGFyc2hhZGFAMjAwNA== # base64 for "Harshada@2004"
